kernel:
  image: linuxkit/kernel:6.12.59
  cmdline: "console=ttyS0 console=tty0"

init:
  - linuxkit/init:b5506cc74a6812dc40982cacfd2f4328f8a4b12a
  - linuxkit/runc:9442aa234715e751a16144f1d4ae3fd1a00fd492
  - linuxkit/containerd:ba19f64efd3331a8fd0a33e00eabd14f6ee1780e
  - linuxkit/ca-certificates:256f1950df59f2f209e9f0b81374177409eb11de

onboot:
  - name: sysctl
    image: linuxkit/sysctl:43ac1d39da329c3567fcb9689e5ca99de6d169b6
    
  - name: sysfs
    image: linuxkit/sysfs:6d5bd933762f6b216744c711c6e876756cee9600
    
  - name: dhcpcd
    image: linuxkit/dhcpcd:b87e9ececac55a65eaa592f4dd8b4e0c3009afdb
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]

  - name: format-workspace
    image: alpine:3.23
    capabilities:
      - CAP_SYS_ADMIN
    binds:
      - /dev:/dev
    command: ["/bin/sh", "-c", "blkid /dev/vdb || mkfs.ext4 -L workspaces /dev/vdb"]

  - name: mount-workspace
    image: linuxkit/mount:bd1c3bb45e48e68e47a9456d1669f7119f855184
    command: ["/usr/bin/mountie", "/dev/vdb", "/workspaces"]

  # Mount config secret disk
  - name: mount-config
    image: linuxkit/mount:bd1c3bb45e48e68e47a9456d1669f7119f855184
    command: ["/usr/bin/mountie", "/dev/vdc", "/run/config"]

services:
  - name: docker
    image: docker:29-dind
    capabilities:
      - all
    net: host
    pid: host
    mounts:
      - type: cgroup
        options: ["rw", "nosuid", "noexec", "nodev", "relatime"]
    binds:
      - /var/lib/docker:/var/lib/docker
      - /var/run:/var/run
      - /workspaces:/workspaces
    command: ["/usr/local/bin/dockerd", "--host", "unix:///var/run/docker.sock", "--storage-driver", "overlay2"]

  - name: getty
    image: linuxkit/getty:a86d74c8f89be8956330c3b115b0b1f2e09ef6e0
    env:
      - INSECURE=true

  - name: sshd
    image: linuxkit/sshd:08e5d4a46603eff485d5d1b14001cc932a530858
    binds:
      - /root:/root
      - /workspaces:/workspaces

  - name: workspace
    image: ghcr.io/ubiquitousbear/codespace:latest
    net: host
    capabilities:
      - CAP_NET_BIND_SERVICE
    binds:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspaces:/workspaces
      - /run/config:/run/config:ro

files:
  - path: /etc/docker/daemon.json
    contents: |
      {
        "storage-driver": "overlay2",
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        }
      }
